apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: beyond-tutorial
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: beyond-tutorial
    app.kubernetes.io/part-of: beyond-tutorial
  name: beyond-tutorial
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: beyond-tutorial
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: beyond-tutorial
    spec:
      containers:
      - image: python-image:latest
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 8000
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
